project:
  name: workload
  regions:
    - eu-central-1
    - eu-west-1
    - us-east-1
    - us-west-2
  s3_regional_buckets: True
tests:
  default:
    template: ./templates/workload.template.yaml
    regions:
    - eu-central-1
    parameters:
      QSS3BucketRegion: '$[taskcat_current_region]'
      QSS3BucketName: '$[taskcat_autobucket]'
      QSS3KeyPrefix: 'quickstart-softing-edgeconnector-siemens/'
      PublicSubnet1ID: 'subnet-06e5f2e1803d84754'
      PublicSubnet2ID: 'subnet-036ac5d35bfed6466'
      VPCID: 'vpc-0f324555fa6935444'
