// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There are no additional costs for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

The deployment takes about 5-10 minutes. If an error occurs, the deployment ends and the stack is rolled back. You must delete it yourself so that the resources created before the error occurred are deleted. If you encounter deletion errors, try to delete the stack again, or delete the individual elements manually.

After all the necessary resources are created and running, the next step is to go to the AWS IoT SiteWise Monitor page to view the data transfer in a dashboard in the AWS IoT SiteWise portal.

. Sign in to your AWS account, and launch the AWS CloudFormation template.

[cols=2*]
|===
^|https://fwd.aws/GJwzr[Deploy {partner-product-name} on AWS^] 
^|https://fwd.aws/Q5JjB[View template^]
|===

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-short-name} is built. The template is launched in the {default_deployment_region} Region by default.

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. For details on each parameter, see the link:#_parameter_reference[Parameter reference] section of this guide. When you finish reviewing and customizing the parameters, choose *Next*.
