// If no preperation is required, remove all content from here

//==== Prepare your AWS account

//_Describe any setup required in the AWS account prior to template launch_

//==== Prepare your {partner-company-name} account

//_Describe any setup required in the partner portal/account prior to template launch_

==== Prepare for the deployment

===== Deployment configurations

The Softing dataFEED edgeConnector Siemens can be deployed in a virtual configuration only with this quickstart.

====== Fully virtual deployment

The virtual deployment is intended for demonstration, training and evaluation of the product's capabilities. An EC2 instance will be launched to simulate edge gateway hardware but in all other respects the experience will mirror that of the real physical deployment. This deployment mode relies on simulated tag values generated by the software. There are no physical PLCs or sensors that are being connected.

We are aiming to provide a one-click way to start up a package of software components integrated with AWS services for the users to try out both the partner software and the provided AWS services to be able to quickly evaluate them.

===== Data flow

Data ingestion will happen from the edge software component, internally containing and running a Siemens S7 1200/1500 protocol simulator, into AWS IoT SiteWise or other services via AWS IoT Greengrass running also on the edge device and through AWS IoT Core.