// If no preperation is required, remove all content from here

//==== Prepare your AWS account

//_Describe any setup required in the AWS account prior to template launch_

//==== Prepare your {partner-company-name} account

//_Describe any setup required in the partner portal/account prior to template launch_

==== Prepare for the deployment

===== Prerequisites
. *an AWS account*, with permissions to use the services mentioned above, including AWS IoT Core and AWS IoT Greengrass, which are prerequisites for AWS IoT SiteWise, thus not shown in the diagram

. *AWS SSO*: in order to be able to visualise data sent to AWS IoT SiteWise by using its monitoring capabilities (portals and dashboards), the destination AWS account needs to have SSO sign-in capabilities. This is also required if the data is going to be visualised by non-AWS users and accounts. We leave these types of configurations to the user, the CloudFormation template does not provide such configuration, and stack deployment may fail without SSO availability

. *AWS IoT Greengrass service role* with the right permissions: we need the standard (AWSGreengrassResourceAccessRolePolicy) access policy for the Greengrass service role as described here, containing permissions to use secrets. If you already have one set up for your account, but without the mentioned policy, a new role will be created and attached with the necessary policy, replacing the existing one. Also, if there is no service role set, a new one will be created and set for the account.
The Greengrass service role is necessary to allow Greengrass deployments to work with other AWS services; in our case one of them is SecretsManager, in which we store a pair of username and password for the edgeConnector Siemens UA endpoint. Greengrass and SiteWise need to be able to retrieve this information from SecretsManager

. One of the *supported regions*, due to AWS IoT SiteWise's limited availability

===== Deployment configurations

The Softing dataFEED edgeConnector Siemens can be deployed in a virtual configuration with this Quick Start.

====== Fully virtual deployment

The virtual deployment is intended for demonstration, training and evaluation of the product's capabilities. An EC2 instance will be launched to simulate edge gateway hardware but in all other respects the experience will mirror that of the real physical deployment. This deployment mode relies on simulated tag values generated by the software. There are no physical PLCs or sensors that are connected.

We are aiming to provide a one-click way to start up a package of software components integrated with AWS services for the users to try out both the partner software and the provided AWS services to be able to quickly evaluate them.

===== Data flow

Data ingestion will happen from the edge software component, internally containing and running a Siemens S7 1200/1500 protocol simulator, into AWS IoT SiteWise or other services via AWS IoT Greengrass running also on the edge device (EC2 instance) and through AWS IoT Core.