// If no preperation is required, remove all content from here

//==== Prepare your AWS account

//_Describe any setup required in the AWS account prior to template launch_

//==== Prepare your {partner-company-name} account

//_Describe any setup required in the partner portal/account prior to template launch_

==== Prepare for the deployment

===== Prerequisites
Prepare the following components before deploying the Quick Start:

* *An AWS account*: Permissions are required to use the services provided with this Quick Start, including AWS IoT Core and AWS IoT Greengrass, which are both prerequisites for AWS IoT SiteWise.

* *AWS Single Sign-On*: The destination AWS account requires SSO capabilities to visualize data sent to AWS IoT SiteWise through its monitoring capabilities (portals and dashboards). SSO is also required for non-AWS users and accounts to visualize data. Note that the CloudFormation template does not configure SSO. Failure to configure SSO can result in deployment failure.

* *AWS IoT Greengrass service role*: The service role is required for AWS IoT SiteWise and AWS IoT Greengrass to retrieve the {partner-product-short-name} UA endpoint's user name and password, which is stored in AWS Secrets Manager. 

The AWS IoT Greengrass service role also requires the standard access policy (AWSGreengrassResourceAccessRolePolicy) with permissions to use secrets. If a service role is already configured for your account, but without the access policy, a new role will be created with the access policy, replacing the existing one. If you have not yet configured a service role, a new one will be created and set for the account.

* *A supported Region*: A supported Region is required due to the limited availability of AWS IoT SiteWise.

===== Deployment configurations

Use this Quick Start to deploy {partner-product-short-name} in a virtual configuration.

===== Fully virtual deployment

The virtual deployment is intended for demonstration, training, and evaluation of the product's capabilities. An Amazon EC2 instance is launched to simulate edge gateway hardware, but in all other respects, the experience mirrors that of the real physical deployment. This deployment mode relies on simulated tag values generated by the software. No physical PLCs or sensors are connected.

The goal of the Quick Start is to provide a way for you to try out and evaluate both the {partner-product-short-name} software and the associated AWS services.  

===== Data flow

The edge software component contains and runs a Siemens S7 1200/1500 protocol simulator and passes data into AWS IoT SiteWise or other services via AWS IoT Greengrass, which also runs on the edge device (Amazon EC2 instance) and through AWS IoT Core.
