AWSTemplateFormatVersion: 2010-09-09
Description: Creates a new VPC and Softing edgeConnector instance, and deploys into the newly created VPC (qs-1rjac6e1u).
Metadata:
  QuickStartDocumentation:
    EntrypointName: 'Parameters for launching into a new VPC'
    Order: '1'
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: AWS IoT SiteWise configuration
        Parameters:
          - SiteWiseMonitorCreation
      - Label:
          default: VPC network configuration
        Parameters:
          - AvailabilityZones
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
    # SiteWise Configuration
      SiteWiseMonitorCreation:
        default: AWS IoT SiteWise monitor and dashboard for telemetry visualization
    # VPC
      AvailabilityZones:
        default: Availability Zones
    #Quick Start Configuration
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
# SiteWise configuration
  SiteWiseMonitorCreation:
    Type: String
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
    Description: Choose 'No' to skip creation of AWS IoT SiteWise monitor/dashboard
      setup. In this case, telemetry data is shown only in the Asset Measurements
      section.
#VPC
  AvailabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
# Quick Start configuration
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: aws-quickstart
    Description: Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'eu-central-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is 
    hosted. Keep the default Region unless you are customizing the template. 
    Changing this Region updates code references to point to a new Quick Start location. 
    When using your own bucket, specify the Region. 
    See https://aws-quickstart.github.io/option1.html.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/).
    Default: quickstart-softing-edgeconnector-siemens/
    Description: S3 key prefix that is used to simulate a directory for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with a forward slash. 
      See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
    Type: String
#Rules:

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        CreateAdditionalPrivateSubnets: 'false'
        CreateNATGateways: 'false'
        CreatePrivateSubnets: 'false'
        AvailabilityZones:
          !Join
          - ','
          - !Ref AvailabilityZones
        NumberOfAZs: '2'

  SoftingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        SiteWiseMonitorCreation: !Ref SiteWiseMonitorCreation

Outputs:
  UAEndpoint:
    Description: Public default UA endpoint for access with AWS IoT SiteWise.
    Value: !GetAtt SoftingStack.Outputs.UAEndpoint

  edgeConnectorSiemens:
    Description: Public link for secure access to edgeConnectorSiemens local administrator.
      interface
    Value: !GetAtt SoftingStack.Outputs.edgeConnectorSiemens

  SiteWiseAsset:
    Description: AWS IoT SiteWise asset into which data is published.
    Value: !GetAtt SoftingStack.Outputs.SiteWiseAsset

  Postdeployment:
    Description: See the deployment guide for post-deployment steps.
    Value: !GetAtt https://aws-quickstart.github.io/quickstart-softing-edgeconnector-siemens/